name: "Nix CI"

on:
  workflow_dispatch: # manual triggering
  pull_request:
  push:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
      - COPYING

permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Flake check
        run: nix flake check --print-build-logs
