name: "Nix CI"

on:
  workflow_dispatch: # manual triggering
  pull_request:
  push:
    branches: ['main']
    paths: [ '**.nix', '**.lock' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Flake check
        run: nix flake check --print-build-logs
